Fix `ITAB_DUPLICATE_KEY` and CamelCase
sbcgua/ajson pull request #100
Opened 2022-05-03 13:36 UTC by mbtools

PR #96 was incomplete. It covered nested structures but not nested tables. 
- Test case `set_tab_nested_struct` fails with  `ITAB_DUPLICATE_KEY`
- Test case `to_json_nested_table` fails with incorrect JSON

Fix is to use `<root>-name` for the prefix for `convert_struc` and `convert_table` which is the correct value after mapping.

2022-05-05 15:49 UTC, sbcgua requested changes
Very nice catch. A couple of fixes to do above, but very good catch. 

P.S. Unit tests is a super power 💪

2022-05-05 15:49 UTC, sbcgua commented on src/zcl_ajson.clas.testclasses.abap
> +    data li_writer type ref to zif_ajson.
Just merge lo_cut and li_writer into li_cut, as writer is not separated anymore, I just was lazy to fix it in existing UTs

2022-05-05 15:49 UTC, sbcgua commented on src/zcl_ajson_mapping.clas.testclasses.abap
> +    insert |field_more| into table ls_result-struc_data-field_more.
```
`field_more` ?
```
`|...|` is not supported in 731/702 

P.S. @larshp btw the way abaplint didn't catch this

2022-05-05 15:49 UTC, sbcgua commented on src/zcl_ajson_mapping.clas.testclasses.abap
> +      exp = '{"fielddata":"field_value","strucdata":{"fieldmore":["field_more"]}}' ).
This does not pass, probably case mistype
![image](https://user-images.githubusercontent.com/15635498/166961966-72891d84-2718-473d-8209-9468c966348d.png)

2022-05-05 23:07 UTC, mbtools commented
I was found this when stringyfying `zif_abapgit_definitions=>ty_files_tt`. While trying to fix it, I broke other UTs, so I knew my solution wasn't correct until I got all green. 😄

2022-05-06 09:12 UTC, sbcgua approved these changes

2022-05-06 09:13 UTC, sbcgua commented
Cool. Merging. :) Thanks for the fix.

P.S. just a side question, what do you think about #101 ? (I saw it in one of your commits)

2022-05-06 09:14 UTC, merged