Fix syntax error in ZCL_AJSON in 7.02
sbcgua/ajson pull request #134
Opened 2022-09-23 14:52 UTC by schneidermic0

Closes #133

2022-09-23 19:41 UTC, sbcgua requested changes
Good point, thank you ! One small request, could you please restyle the indentation, and I'll merge.

2022-09-23 19:41 UTC, sbcgua commented on src/zcl_ajson.clas.testclasses.abap
> +                                        act = li_cut->is_empty( ) ).
Could you please indent it to the next line (2 space from cl_...) like the `li_cut->set` below

2022-09-23 19:42 UTC, sbcgua commented on src/zcl_ajson.clas.testclasses.abap
> +                                        act = li_cut->is_empty( ) ).
And the second call as well

2022-09-24 06:15 UTC, larshp commented on src/zcl_ajson.clas.testclasses.abap
> +                                        act = li_cut->is_empty( ) ).
I've opened https://github.com/abaplint/abaplint/issues/2702

2022-09-24 07:42 UTC, schneidermic0 commented on src/zcl_ajson.clas.testclasses.abap
> +                                        act = li_cut->is_empty( ) ).
Sure. Done.

2022-09-24 07:42 UTC, schneidermic0 commented on src/zcl_ajson.clas.testclasses.abap
> +                                        act = li_cut->is_empty( ) ).
Sure. Done.

2022-09-24 11:17 UTC, sbcgua approved these changes

2022-09-24 11:17 UTC, sbcgua commented
Thanks ! Nice fix, merging :)

2022-09-24 11:17 UTC, merged