Performance: Speed-up parsing
sbcgua/ajson pull request #143
Opened 2023-01-08 20:55 UTC by mbtools

Using string instead of stack to handle path makes benchmark 3.4% faster.

2023-01-09 16:59 UTC, sbcgua commented
![image](https://user-images.githubusercontent.com/15635498/211364215-b4a3de8f-044f-4e01-b136-ba2a95af7302.png)

Yeap ~2%

Consistency check is important, let it stay. Don't trust external data :)

2023-01-09 17:02 UTC, sbcgua requested changes
Nice small improvement :+1: Just a couple of comment above

2023-01-09 17:02 UTC, sbcgua commented on src/zcl_ajson.clas.locals_imp.abap
> +    data mv_path type string.
I'd propose renaming as it is too generic. Maybe `mv_stack_path` (probably my preference, because it shows the relation with the stack above) or `mv_current_path`

2023-01-09 17:02 UTC, sbcgua commented on src/zcl_ajson.clas.locals_imp.abap
> +            <item>-path = mv_path.
And maybe leave a comment here that this is a perf optimization. As it is not obvious. Kind of ... string path is faster than rebuilding it from stack ...

2023-01-09 17:23 UTC, mbtools commented
I think inconsistencies already lead to `cx_sxml_parse_error` or `cx_sxml_error` but maybe there are cases `sxml` does not catch.

2023-01-10 09:10 UTC, sbcgua approved these changes

2023-01-10 09:10 UTC, merged