json_to_abap - added logic for type time
sbcgua/ajson pull request #172
Opened 2024-02-02 10:31 UTC by oblomov-dev

never used regex before, but tried to make it as similar as possible to the already existing date logic.

2024-02-02 10:41 UTC, larshp commented on src/core/zcl_ajson.clas.testclasses.abap
> +      reaising cx_static_check.
```suggestion
      raising cx_static_check.
```

2024-02-02 10:45 UTC, oblomov-dev commented on src/core/zcl_ajson.clas.testclasses.abap
> +      reaising cx_static_check.
fixed!

2024-02-04 08:55 UTC, sbcgua requested changes
Looks good, just a couple of polishings

2024-02-04 08:55 UTC, sbcgua commented on src/core/zcl_ajson.clas.testclasses.abap
> +                for testing
Could you pls indent it to the left (as above).

P.S. sorry, I'm a bit picky about readability (indentation in particular)

2024-02-04 08:55 UTC, sbcgua commented on src/core/zcl_ajson.clas.testclasses.abap
> +      exp = '111111' ).
Please add a test with empty value. It should work accroding to the code, but better to have the test. In the same method would be just OK.

2024-02-04 09:16 UTC, oblomov-dev commented
thank you for reviewing!

2024-02-04 12:31 UTC, sbcgua approved these changes
Nice. Merging. Thanks for the catch and fix

P.S. will see the perf issues later, seems they are not 5 min answers ...

2024-02-04 12:34 UTC, sbcgua commented
@larshp abaplint UTs are failing, looks like different `initial time` behavior. Any quick suggestion? (exclude is an option too)

2024-02-04 13:22 UTC, larshp commented
empty value will trigger the exception right? that is then ignored and initial values given?

2024-02-04 14:08 UTC, larshp commented
fixed, running

2024-02-04 16:58 UTC, sbcgua commented
Thanks Lars !

2024-02-04 16:58 UTC, merged

2024-02-04 17:04 UTC, sbcgua commented
Using the occasion, v1.1.10