JSON_TO_ABAP: fix compressed JSON array to sorted/hashed table keeping components problem
sbcgua/ajson pull request #182
Opened 2024-07-03 07:24 UTC by thorsten-wolf-neptune

This PR reproduces the issue that is tracked https://github.com/sbcgua/ajson/issues/181 and contains a fix proposal.

2024-07-03 07:43 UTC, larshp commented
perhaps move the CLEAR up to below code, to have less impact on performance

![image](https://github.com/sbcgua/ajson/assets/5888506/9b6c80bb-b553-49f7-95ce-f443a408acf5)

2024-07-03 07:52 UTC, thorsten-wolf-neptune commented
tried that at first but that is outside of the loop of the array items so it wouldn't work 
https://github.com/sbcgua/ajson/pull/182/commits/3bbb2d7f4040f4fa9ff1961b96d787b71fb590d3#diff-018e6f26075d703b00b41a45a1c76360a17a8ce9846d7314b7b71c9a151f71b5R856

2024-07-08 06:01 UTC, larshp commented
@sbcgua

2024-07-09 09:11 UTC, sbcgua requested changes
Good catch, thank you for the analysis and fix. And good UTs!

I would just suggest moving the `clear` a bit above to `if` at 887 line. Cannot add a commit directly to your branch

![image](https://github.com/sbcgua/ajson/assets/15635498/d1c1db93-7a10-437d-8425-ede36ddd3d46)

2024-07-09 13:08 UTC, thorsten-wolf-neptune commented
Thx :-) i only noticed it because in abapgit we have "skip initial fields" set to true for some TABU entries and when pulling it to a new system the tables where completely messed up :-)

@larshp once that is merged/fixed abapgit would need to also get the mirror updated or?  Should i create an issue there too?

2024-07-09 13:24 UTC, sbcgua approved these changes
👍

2024-07-09 13:25 UTC, merged

2024-07-09 19:20 UTC, larshp commented
https://github.com/abapGit/abapGit/pull/6977