Add diff utility
sbcgua/ajson pull request #28
Opened 2020-11-02 22:57 UTC by mbtools

2020-11-14 13:46 UTC, sbcgua commented
same here, will have a look soon. Sorry for absence

2020-11-29 10:08 UTC, sbcgua requested changes
Generally is OK. Just please adapt to the new `set` version and add some docs pls.

2020-11-29 10:08 UTC, sbcgua commented on src/zcl_ajson_utilities.clas.abap
> +    if iv_json_a is supplied and io_json_a is supplied.
better to use XOR here, because both empty would be an error, but will not raise

`boolc( json is supplied ) = boolc( str is supplied )` -> neither or both

2020-11-29 10:08 UTC, sbcgua commented on src/zcl_ajson_utilities.clas.abap
> +              mo_change->set_with_type( iv_path = <ls_node_b>-path && <ls_node_b>-name && '/'
A kind request to align it under the method. I truly think this a far more readable approach

Although it seems abap world does not always agree with it  - https://github.com/SAP/styleguides/issues/21

2020-12-03 01:41 UTC, mbtools commented
I think that covers it. Now we can quickly find out what Lars changed in the abaplint.json schema :-)

2020-12-11 20:17 UTC, merged

2020-12-11 20:17 UTC, sbcgua commented
merging, thanks ! sorry for delays ...