Test: Camel case first lower case
sbcgua/ajson pull request #46
Opened 2021-01-13 16:24 UTC by jrodriguez-rc

2021-01-13 20:36 UTC, sbcgua requested changes
one typo above, the rest is fine

2021-01-13 20:36 UTC, sbcgua commented on src/zcl_ajson_mapping.clas.testclasses.abap
> +      to_json_fist_lower for testing raising zcx_ajson_error.
typo ?

2021-01-13 20:40 UTC, jrodriguez-rc commented on src/zcl_ajson_mapping.clas.testclasses.abap
> +      to_json_fist_lower for testing raising zcx_ajson_error.
What typo?

2021-01-13 20:43 UTC, sbcgua commented on src/zcl_ajson_mapping.clas.testclasses.abap
> +      to_json_fist_lower for testing raising zcx_ajson_error.
to_json_fist_lower - to_json_first_lower :)

2021-01-13 20:55 UTC, jrodriguez-rc commented on src/zcl_ajson_mapping.clas.testclasses.abap
> +      to_json_fist_lower for testing raising zcx_ajson_error.
Argh! I see it now, I'll fix it in the morning to let it ready to merge

2021-01-14 07:49 UTC, jrodriguez-rc commented
> one typo above, the rest is fine

Done

2021-01-14 08:27 UTC, sbcgua approved these changes

2021-01-14 08:28 UTC, sbcgua commented
Thanks ! :+1:
merging

2021-01-14 08:28 UTC, merged