Fix ITAB_DUPLICATE_KEY when using hashed table
sbcgua/ajson pull request #59
Opened 2021-05-11 16:50 UTC by mbtools

Closes #58

2021-05-15 19:54 UTC, sbcgua commented
Nice fix, thanks !
Could you pls add a UT for it.

2021-05-15 19:55 UTC, sbcgua requested changes
Could you pls add a UT for the hashed table

2021-05-17 11:09 UTC, mbtools commented
done

2021-05-17 13:53 UTC, sbcgua requested changes
Almost there :)

2021-05-17 13:53 UTC, sbcgua commented on src/zcl_ajson.clas.testclasses.abap
> +    insert |world| into table lt_tab.
![image](https://user-images.githubusercontent.com/15635498/118500174-404c7d80-b730-11eb-96be-6b29cac990ce.png)

731 does not support string templates inserts.

2021-05-17 16:53 UTC, mbtools commented on src/zcl_ajson.clas.testclasses.abap
> +    insert |world| into table lt_tab.
the usual... you make a change and go away fully believing you knew it works. well, it should now.

2021-05-17 20:54 UTC, sbcgua commented on src/zcl_ajson.clas.testclasses.abap
> +    insert |world| into table lt_tab.
I nearly missed it as well. The code looked good. And I nearly clicked merge button but then decided to test it :)

2021-05-17 20:54 UTC, sbcgua approved these changes
Now it's good, thanks ! Merging

2021-05-17 20:55 UTC, merged