Refactor input check for utilities
sbcgua/ajson pull request #93
Opened 2022-01-03 01:40 UTC by mbtools

Consolidate 3 checks into 1 method

2022-01-03 10:21 UTC, sbcgua requested changes

2022-01-03 10:21 UTC, sbcgua commented on src/zcl_ajson_utilities.clas.abap
> +  method check_input.
Maybe I'd refer `normalize_input` because it does not only check it but actually converts. The rest looks good :)

2022-01-07 13:12 UTC, mbtools commented on src/zcl_ajson_utilities.clas.abap
> +  method check_input.
done

2022-01-08 13:57 UTC, sbcgua commented
👍

2022-01-08 13:58 UTC, merged