Add merge utility
sbcgua/ajson pull request #94
Opened 2022-01-03 01:52 UTC by mbtools

After #93

New method to merge two JSON objects

2022-01-03 10:23 UTC, sbcgua requested changes
rebase after #93 ?

2022-01-08 13:58 UTC, sbcgua commented
probably should be rebased once more. 93 was merged.

2022-01-10 16:05 UTC, mbtools commented
should be ok now

2022-01-10 22:29 UTC, sbcgua commented
Yeap, merging :+1:

2022-01-10 22:29 UTC, merged